version: '3.7'

services:
  gitea:
    image: gitea/gitea:latest
    restart: always
    volumes:
      - ./data/gitea:/data
    environment:
      USER_UID: '1000'
      USER_GID: '1000'
      DB_TYPE: sqlite3
      DB_NAME: gitea
    ports:
      - '3000:3000'
      - '2000:22'
