version: '3.7'

services:
  gitea:
    image: gitea/gitea
    restart: always
    volumes:
      - ./data:/data
    environment:
      USER_UID: '1000'
      USER_GID: '1000'
      DB_TYPE: sqlite3
      DB_NAME: gitea
      RUN_MODE: prod
      ROOT_URL: https://code.example.com/
      SSH_DOMAIN: code.example.com
      APP_NAME: 'Gitea: Git with a cup of tea'
    ports:
      - '22:22'
    networks:
      - internal
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx:/etc/nginx
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - internal
    ports:
      - '80:80'
      - '443:443'
networks:
  internal:
