version: '3.7'

services:
  gitea:
    image: gitea/gitea:latest
    restart: always
    volumes:
      - ./data:/data
    environment:
      USER_UID: '1000'
      USER_GID: '1000'
      DB_TYPE: sqlite3
      DB_NAME: gitea
      RUN_MODE: prod
      ROOT_URL: http://localhost/
      APP_NAME: Local Gitea
    ports:
      - '222:22'
    networks:
      - internal
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - internal
    ports:
      - '8080:80'
networks:
  internal:
